### ISSUE TITLE
Why java over cordova or react native

### ISSUE THREAD

**Issue by binyamin** [johannesjo/super-productivity-android#1]

**Comment by johannesjo** [comment]
The app is already written (without react native or angular native script) as web app and I don't want to rewrite the whole thing :)

**Comment by binyamin** [comment]
iirc, Cordova supports vanilla html/css/js.

**Comment by johannesjo** [comment]
There are some things which can't be done (easily) with cordova: 
1. Providing a Widget (which currently is the single most important reason, why this apps exists)
2. Serving the webapp instead of a local bundle to make service workers etc possible
3. google auth (possible, but complicated)

Furthermore, the app is much much smaller without the whole cordova lib. Also, Cordova is a big mess in my experience (and I've developed some applications with it) :)
