### ISSUE TITLE
lack of LocalFile sync on Android versions.

### ISSUE THREAD

**Issue by tzawlxih** [johannesjo/super-productivity-android#13]
### :speaking_head: Foreword

Thank you so much for great app, today i've switched to it from taskwarrior and gnome-pomodora because got tired of its bugs after each gnome update.

## 🙍🏽 Problem Statement

The Android (both F-Droid and GPlay versions) lack critical feature for me the LocalFile sync in order to can keep same copy of tasks on both devices.

## :grey_question: Possible Solution

Can you please add LocalFile sync.

## :arrow_heading_up: Describe alternatives you've considered

As an alternative maybe we can specify our own path for user_data if it is compatible with PC version.

**Comment by johannesjo** [comment]
Thanks for reporting this! Help with it would be very welcome!

**Comment by detectivepikachu** [comment]
What exactly is the status of this issue? I did look at the two references and seems there like there was a merge for this but I cannot see it on at least the fdroid version. What can we do about it?

**Comment by johannesjo** [comment]
The app is currently stuck in the submission process at the play store :( I already tried to contact them about the issue. Currently that means, that you have to build the android apk for yourself :( Not sure how to proceed tbh. I will try to reach out to them once more, hopefully they understand why the permission might be crucial.

That's the email I got:

Hi Developers at The Front End,
After a recent review, we found that your app Super Productivity (com.superproductivity.superproductivity) is not compliant with one or more of our Developer Program Policies. See below for more information about your app's status and how to correct the issue.


App Status: Rejected
Your app has been rejected and wasn't published due to the policy issue(s) listed below. If you submitted an update, the previous version of your app is still available on Google Play


Issue found: Not a core feature
The feature you identified that is dependent on this permission does not appear to be critical to the core functionality of your app.

Core functionality is defined as the main purpose of the app. Without this core functionality, the app is "broken" or rendered unusable. The core functionality, as well as any core features that comprise this core functionality, must all be prominently documented and promoted in the app's description.

Please update your app so that the feature does not use this permission or ensure that the core functionality is prominently documented and promoted in the app's description and resubmit your app on Play Developer console.

Additionally, follow these steps to bring your app into compliance:

Read more about [Use of All Files Access](https://notifications.google.com/g/p/AM0OvepFlTjBcB20q9MHVjj0qzKe9iz_nwhPUKLYA4P6cq0zxzGmN1nSE7EklU9MEwMuUePdvPpU1v4YmYlNeaYnLQaRruLM4XcmqSY1WRHJNLMQKu6A4AWhi8cC0vHea-vTjfI6WJ-J_RM0) Permission
See [Android storage use cases and best practices](https://notifications.google.com/g/p/AM0Oveqq-Ijk_KcEpVe9_Og19r0OBZlKNGG_72LloJqsQHk2dnONKIeEMeQ_gd3LuLhVQuekVsCzJ_7OlnojekG22EPngXeixhXDe0fOw5If91dNMahnp1OT3Cozah4uusyF)
About the All Files Access Permission Policy
Files and directory attributes on a user's device are regarded as personal and sensitive user data subject to the [Personal and Sensitive User Data](https://notifications.google.com/g/p/AM0OveqtuYUUnh0cdUarf8mBOtFjeNbqKhYCoQEnYo1HH98zRFxMqE9EwyT4KdBQfaH7kaLd8KSJ9q0k-aOWFqNSqCKOR3Gy3vcyuY_RL0R3kC2sY_Vv1msrDVZRm-E6R0AL6TaODGhJmi8b9w) policy and the following requirements:
Apps should only request access to device storage which is critical for the app to function, and may not request access to device storage on behalf of any third-party for any purpose that is unrelated to critical user-facing app functionality.
Android devices running Android "R" (Android 11) or later, will require the [MANAGE_EXTERNAL_STORAGE](https://notifications.google.com/g/p/AM0OverswyBRRXbFsFV-rLBoik2eQx7yvUT9ox5oaFLcIrPBGE7LBAM6mbzMZ7CK7ShCeCFinDuQGpguMcKYMeQsVfBHVAPHSndwqdAOJptDPxBPewBiyt2FSDLs74sjk474TvBm4F84vfA-Z6v6uIGMUsOw1RYfdPPn6HIS5HIw) permission in order to manage access in shared storage. All apps that target R or later and request broad access to shared storage ("All files access") must successfully pass an appropriate access review prior to publishing. Apps allowed to use this permission must clearly prompt users to enable "All files access" for their app under "Special app access" settings. For more information on the R requirements, please see this [help article](https://notifications.google.com/g/p/AM0OvepFlTjBcB20q9MHVjj0qzKe9iz_nwhPUKLYA4P6cq0zxzGmN1nSE7EklU9MEwMuUePdvPpU1v4YmYlNeaYnLQaRruLM4XcmqSY1WRHJNLMQKu6A4AWhi8cC0vHea-vTjfI6WJ-J_RM0).


Action required: Submit an updated app for review
Here's what to do to help get your app on Google Play:
Make sure to read the applicable policies or requirements listed below:
[All Files Access Permission Policy](https://notifications.google.com/g/p/AM0OveoN7S-WoEeX_kvsc5qmSWNR-LEKtxZf65BfTvzdR9FT_JccQXnxPDiZAWP27BI-aOJYJbz9hV68FoEQLvvAT9vgKLXdDQDS4oFIQ8jYmhDkbXEdJTzw8bTDo1Xjdj3X5xe2O74l_WQw6LXI3oUdlhgA21IZO30rLQ)
Make appropriate changes to your app (if possible), and be sure to address the issue described above. You may also want to check your app's store listing for compliance, if applicable.
Double check that your app is compliant with all other [Developer Program Policies](https://notifications.google.com/g/p/AM0Ovep4yYH6n98HAZp9p3yyAGgHL_YglBAMriDtdBd8hjDeMmOK1v1zE_S4DERZs6izuM-wPUUK7g6wBHrkLCMwz2qBaTrXRRV9Hb1qeP3X7y-fzPg1E4EMpDA_yxLQdg).
If you made changes to your app bundle, store listing, or APK, please sign in to your [Play Console](http://notifications.google.com/g/p/AM0OveqNNwDmWgDoM6UkSk8DQoQmg53vF9vK8bJ9UMEt2gMJTAOPfsSej3rT2mM8dvgFYPc0i66Mu9sKhiwfZchSczvf9e1G18m7VnYoMp3pSRgEzyIolYq-CyL1WEee-NUKDI3bfNsmKA-b_Q3CSG-rveT1IMmDAdpVY79u-iBFGw) and submit the update(s).
Contact support
If you've reviewed the policy and feel our decision may have been in error, please reach out to our [policy support team](https://notifications.google.com/g/p/AM0Over_8pzqUJLng5uopwkFWidR-iWKEs6L6UVFxbKC6Tq2mM9_NvT0LqLhT6BUMRgfgGGrSC7G2E68rYFwESQVUbNfrrQwyl5_I_njbNpZrvHX4Qvhka2RKOc2Xabn9nYE6J1hC-orx1lcu0cLgEbdDq8BipTRF0aBb_d_dz2BNJoQ2uuOQBuDDuI). We'll get back to you within 2 business days.

**Comment by detectivepikachu** [comment]
Okay but even f-droid is not allowing it? I cannot see that feature on f-droid as well? 

Also for the permission: From the email it seems like we need to mention it well in the description. So is it just that the app description(like the one on the app stores in paragraph form) that you send them needs to be modified in a way so the readers are convinced enough. Am I on the right track? If that's the case then we could help you with it maybe?

And for noobs can you please explain or give a link for "building the app yourself"? I have no idea what to do to build the apk.

**Comment by johannesjo** [comment]
I reached out to them again describing the situation. Let's see.

Not sure about the FDroid version. Maybe someone actually using it can help?

**Comment by detectivepikachu** [comment]
Oh okay let's hope for the best then I guess. But anyways thank you so much for this life saving tool! The features this app has are just way beyond than the proprietary apps!

**Comment by detectivepikachu** [comment]
I finally was able to build the apk for the app and point it to https://app.super-productivity.com/ but it still does not have the local sync feature. Did I miss something?

**Comment by johannesjo** [comment]
Hey hey! Sorry for the very delayed reply (I was a bit busy over the holidays). Seems like there broke something during the merge of the last PR. I made some adjustments and it should work for the fdroid flavor too, though it seems that there are still some issues with the feature :/

**Comment by lrq3000** [comment]
Google will never accept the app with this permission. Since Android 11, apps must use scoped storage, which is a new API which requires that the app asks for permission before using a file or folder that is outside its private storage space (that is inaccessible to other apps). The permission `MANAGE_EXTERNAL_STORAGE` is reserved to apps that really need to have rights over ALL files, such as files managers.

There is a library called [SimpleStorage](https://github.com/anggrayudi/SimpleStorage) that simplifies the handling of permission requests on Android. If I have enough time, I may have a look to implement it here.

**Comment by johannesjo** [comment]
@lrq3000 Thanks for the insights. Would be great if you could have a look. Since google drive sync will stop to work in a month we sure could use another option in place for syncing.

**Comment by zoli** [comment]
> I finally was able to build the apk for the app and point it to [app.super-productivity.com](https://app.super-productivity.com/) but it still does not have the local sync feature. Did I miss something?

Is it still the case that local sync not working on your own build version of apk? It works well for me.

**Comment by lrq3000** [comment]
@zoli I think it worked but only if the permission was given, and sometimes Android can disable permissions it deems unnecessary, especially if some time has passed without using the app. This often bites developers trying debug APKs on real devices (it happened to me recently).

Anyway I now re-implemented the feature with scoped storage permission. Thanks to your previous work, all the functions were already implemented, I just reworked them to use the SimpleStorage library instead of the File java api, thank you very much @zoli! :D

Please guys test my PR, I only discovered Super Productivity recently and I am not using it since it could not save on Android, so I don't know all features. It seems to work fine for me, but if there is any issue, please let me know and I'll have a look, file access should not be an issue anymore with SimpleStorage.

**Comment by zoli** [comment]
@lrq3000 Thanks for the effort, Having this feature in official version on play store would be great. 
Just to learn STH here. Android still lets you have permission to read and write any folder which you specifically ask for the permission and thats what SimpleStorage helps us to achive right?
So `MANAGE_EXTERNAL_STORAGE` gave permission to read and write whole storage and that is restricted in recent android versions but having permission for specific chosen directory is possible.

**Comment by lrq3000** [comment]
@zoli Yes exactly, with some caveats and limitations. Essentially, when we use scoped storage, we not only ask for permission, but we also signal to Android that this folder is now associated with our app, so that when the user uninstalls our app, Android can also tell the user that the folder can now be deleted. So we can't choose just any folder, in fact we can't select the root nor system folders nor private folders of other apps, but we can select folders that are in unprotected areas or in shared folders (ie, Download folder). The goal is to avoid all apps to have access to everything and making a mess of your filesystem. In theory, that's nice, but the API they made is super messy and poorly documented, that's why SimpleStorage is so awesome, it's the facade API that Google should have made but didn't. You can read more about the original purpose for scoped storage here: https://source.android.com/docs/core/storage/scoped
