### ISSUE TITLE
File sync not working for android versions below Q

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity-android#36]
Hey hey @lrq3000 ! Could I maybe ask you to have another look at this? I am try to get this to work on my phone which runs on android 9. Unfortunately there the permissions dialog is never opened and without it it doesn't seem to be able to write the file.

**Comment by lrq3000** [comment]
Hey @johannesjo, by file upload do you mean filesync? If yes, then that's normal, because scoped storage is only implemented in android 10+ so we open the folder picker dialog only on these, but for lower versions it uses the old permission system. I did not test with Android 9, if it doesn't work, then we can just change the condition to lower:

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O)

To:

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P)

For Android 9.

I'll try various versions of android to ensure if it all works as expected for older versions, I'll post here my results.

2 févr. 2023 20:46:20 Johannes Millan ***@***.***>:

**Comment by johannesjo** [comment]
Yes sorry! File sync of course! I tried changing the if condition, but that didn't do the trick. Would be great if you could have another look at this!

**Comment by lrq3000** [comment]
Ok i see then maybe a regression was introduced somewhere, I'll have a look, thanks for the heads up.

3 févr. 2023 13:34:50 Johannes Millan ***@***.***>:

**Comment by lrq3000** [comment]
@johannesjo I get a fatal error on just opening SP on Android 9: https://github.com/johannesjo/super-productivity/issues/2451

Do you get the same?

I also tested Android 10, no problem there.
